### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by lourkeur** [libmpack/libmpack#22]
When building the lua library (10.3.3) on Arch Linux x86-64, I had `leak_test.lua` report a 128 kilobytes leak with lua 5.2.4 and 5.3.3, but not with 5.1.5. I don't really know anything else for now. To reproduce:
```sh
sudo pacman -S lua51 lua52 lua luarocks5.1 luarocks5.2 luarocks
git checkout 1.0.3
cd binding/lua
# this scraps the preexisting makefile
cat > Makefile << "END"
VERSION?=5.1
LUAROCKS=/usr/bin/luarocks-$(VERSION)
LUA=/usr/bin/lua$(VERSION)

test:
	eval `$(LUAROCKS) path`; \
	$(LUAROCKS) build mpack --local
	eval `$(LUAROCKS) path`; \
	valgrind --log-file=valgrind.log-$(VERSION).txt

 --leak-check=yes --track-origins=yes $(LUA) leak_test.lua
END
make
# ok
make VERSION=5.2
# fail .. leaked 128 kilobytes
make VERSION=5.3
# fail .. leaked 128.0 kilobytes
```

Hope I can help track this down by providing more details if requested. Please find attached the logs I was able to gather.

[valgrind.log-5.1.txt](https://github.com/tarruda/libmpack/files/706267/valgrind.log-5.1.txt)
[valgrind.log-5.2.txt](https://github.com/tarruda/libmpack/files/706268/valgrind.log-5.2.txt)
[valgrind.log-5.3.txt](https://github.com/tarruda/libmpack/files/706269/valgrind.log-5.3.txt)

**Comment by lourkeur** [comment]
Also I seem unable to reproduce it on Ubuntu via Travis:
+[5.3.3 has an unrelated error](https://travis-ci.org/lourkeur/libmpack/jobs/191980822)
+[5.2.4 doesn't exhibit the leak](https://travis-ci.org/lourkeur/libmpack/jobs/191985032)

**Comment by tarruda** [comment]
Can you still reproduce this on https://github.com/libmpack/libmpack-lua ?

**Comment by lourkeur** [comment]
looks like it, yeah, on commit 64a46dfdcef7d1a2287d11aa03d9cae058889df1:
[valgrind.log-5.1.txt](https://github.com/libmpack/libmpack/files/856376/valgrind.log-5.1.txt)
[valgrind.log-5.2.txt](https://github.com/libmpack/libmpack/files/856377/valgrind.log-5.2.txt)
[valgrind.log-5.3.txt](https://github.com/libmpack/libmpack/files/856381/valgrind.log-5.3.txt)
That's weird, even weirder if I'm the only one who sees it. Maybe it's on the arch packages?

Lua 5.1 also self reports `ok`, lua5.2 and 5.3 still say they leaked 128 kilobytes. I'm going to try having `run()` called multiple times on 5.3 to see if it leaks proportionally more memory. I'll also try on a different computer tomorrow.

**Comment by lourkeur** [comment]
logs side-by-side:
https://gist.github.com/lourkeur/e628f844c24ea5cec5851570186ebd53/revisions

**Comment by lourkeur** [comment]
It does leak 384 kilobytes with three `run()` lines between the `before` and `after` lines, although the numbers valgrind reports are the same. I've got to try 1000 times to see if it totally blows up the vm or not...

[valgrind.log-5.3.txt](https://github.com/libmpack/libmpack/files/856470/valgrind.log-5.3.txt)

**Comment by lourkeur** [comment]
Ok, I just ran the test with a loop with 4000 iterations of run() on lua 5.3, and its memory usage stayed at around 175Mb for 15 minutes, rather than climbing up to 512Mb.  This most likely comes down to garbage collection algorithm tradeoffs subtleties, so there is no critical bug in libmpack-lua, indeed no bug at all, it's just that the GC doesn't do what we want it to do when `collect` is called. This means the test is unpredictable and broken. Maybe we had better count the integer keys inside the Lua registry as `before` and `after` measurements? I'll look into it tomorrow
