### ISSUE TITLE
python unpacker segfaults on {True: True}

### ISSUE THREAD

**Issue by lourkeur** [libmpack/libmpack#27]
The python binding segfaults with the following output when passed `b"\x81\xc2\xc2` for unpacking:
```
Exception ignored in: 'mpack.Registry.ref'
Exception: Object is already referenced
Segmentation fault (core dumped)
```
It seems to occur only when a key maps to itself in a map, with "itself" meaning the same object. (`key is value`) It also doesn't occur in arrays, nor when the lua binding is used.  Also I have only tried Python 3.6.0 on GNU/Linux.

I have some testcases at [lourkeur:issue23](https://github.com/lourkeur/libmpack/tree/issue23). (can't use Python frameworks because the segfault messes them all up.)  The CI is currently broken (shall I look into it?), but you may want to try them on your local machine.  The CI does prove the point about Lua though.

AFAIK the exception comes from [this line](https://github.com/tarruda/libmpack/blob/python-binding/binding/python/mpack.pyx#L99), but I don't know Cython so it's probably better if you (@tarruda ) investigate since you wrote it.

For the record, I came across this as I was writing [Hypothesis](http://hypothesis.works) strategies for the python binding.  Still WIP, may do a PR later tonight.  In any case, thank you for the Python binding, because I believe a fuzzer such as Hypothesis is an excellent thing to have.

**Comment by tarruda** [comment]
That's great, thanks for testing the python binding before it is ready!

I still didn't had time to merge the python binding, but I'm planning to push into a separate repository in the [libmpack org](https://github.com/libmpack).

**Comment by lourkeur** [comment]
Gee! I didn't realize I was that much of an early adopter. I seem to be unable follow the org or do anything on its [page](https://github.com/libmpack), is that intended? No rush, I just want to be notified when it happens.

Can confirm the bug on Python 2.7.13 on GNU/Linux, unsurprisingly.

I'll keep the hypothesis cases on a separate branch until the binding is ready. Again no rush, it's just interesting for me to learn a bit about Hypothesis by doing. Afterwards I'll be glad to MIT it and maintain it if you like.

**Comment by tarruda** [comment]
The repository is now https://github.com/libmpack/libmpack-python and this issue should be fixed
