### ISSUE TITLE
Ignore "can't serialize object"

### ISSUE THREAD

**Issue by teto** [libmpack/libmpack#30]
I want to use libmpack to generate an mpack file from a lua table (this table https://github.com/neovim/neovim/blob/master/src/nvim/options.lua#L44) but i run into:
`binding/lua/lmpack.c 'can't serialize object'`

One option is to clean the lua table, the other one would be to tell mpack to either ignore or serialize the errors instead, as it can be done in other libraries. It makes prototyping easier.

**Comment by tarruda** [comment]
👍 

I will try to implement this for the next version

**Comment by teto** [comment]
Great, for now I've dropped the problematic keys so no hurry :)
