### ISSUE TITLE
Status of Project

### ISSUE THREAD

**Issue by chetgurevitch** [libmpack/libmpack#35]
@tarruda @justinmk
I ran into some issues building the lua bindings and sent in a [pr](https://github.com/libmpack/libmpack-lua/pull/4) which should resolve them. I noticed there hasn't been any activity since around march and as I understand things @tarruda has had less time for neovim and related projects. I don't really know much in the way of C but I'm down to help out with the build-system issues and/or project management stuff if you guys are good with that. Also sorry if this is coming off as pushy or anything, just looking to help.

**Comment by tarruda** [comment]
For some reason I was not watching libmpack-lua repository and didn't receive email notifications, so I'm sorry for the delay.
