### ISSUE TITLE
Is libmpack thread safe?

### ISSUE THREAD

**Issue by moiri** [libmpack/libmpack#45]
I was wondering if `libmpack` is thread safe. I cannot find any comment/documentation on this.

**Comment by tarruda** [comment]
There's no global memory, so you can use separate instances of the structures in different threads. You cannot share the same `mpack_rpc_session_t` or `mpack_parser_t`  across threads without some external thread synchronization.

**Comment by moiri** [comment]
Cool, thanks for your reply!
